apiVersion: v1
kind: Secret
metadata:
  name: personal-website
type: Opaque
data:
  storage-connectionString: {{ .Values.secrets.azureStorageConnectionString | b64enc | quote }}
  db-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson | b64enc | quote }}
