apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghost-helm-chart.configMapName" . }}
  labels:
    {{- include "ghost-helm-chart.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.app.conf }}
  {{ $key | snakecase | upper }}: {{ $value | quote }}
{{- end }}
