{{- $encryptionKey := .Values.encryptionKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretsName }}
  labels:
    {{- include "ghost-helm-chart.labels" . | nindent 4 }}
type:
  kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imageRegistryDockerConf | replace "\n" "" | decryptAES $encryptionKey | quote }}
