apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ghost-personal
  namespace: ghost
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
  - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
