apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-helm-chart.secretName" . }}
  labels:
    {{- include "ghost-helm-chart.labels" . | nindent 4 }}
stringData:
{{- $encryptionKey := .Values.encryptionKey -}}
{{ range $key, $value := .Values.secrets }}
  {{ $key | snakecase | upper }}: {{ $value | replace "\n" "" | decryptAES $encryptionKey | quote }}
{{- end }}
